import { Inter } from "next/font/google";
import "./globals.css";
import 'boxicons/css/boxicons.min.css';
import Header from "../components/Header";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome to my Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( 
  
    
    <html lang="en">
     
    

    
      <body className={inter.className}>  
      <Header />
      {children}</body>
    </html>
    
  );
}
